// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP_hq0Yf_FBPRAimAzN4LqPpNHmcgDhzk',
    appId: '1:18822208753:web:beed2111a3cc8da2af9d50',
    messagingSenderId: '18822208753',
    projectId: 'authentication-7f3fc',
    authDomain: 'authentication-7f3fc.firebaseapp.com',
    storageBucket: 'authentication-7f3fc.appspot.com',
    measurementId: 'G-S6BX72L5P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkAy2f0BsXzaqZLdZpK8gPZ-t2UHXDQgY',
    appId: '1:18822208753:android:f6546a44fa9914ccaf9d50',
    messagingSenderId: '18822208753',
    projectId: 'authentication-7f3fc',
    storageBucket: 'authentication-7f3fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaY6t8rWW7zmQyjoB1wgMv73QUlGRGF7k',
    appId: '1:18822208753:ios:b50e385fee470f44af9d50',
    messagingSenderId: '18822208753',
    projectId: 'authentication-7f3fc',
    storageBucket: 'authentication-7f3fc.appspot.com',
    iosClientId: '18822208753-h556caqm5pr7gt5r8d0gj0tm62g6q1ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.denemeFlutter',
  );
}
